'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("atcWCS.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Num Cropping-GIRAS:	21
        '''11	Residential
        '''12	Commercial And Services
        '''13	Industrial
        '''14	Trans, Comm, Util
        '''15	Indust &amp; Commerc Cmplxs
        '''16	Mxd Urban Or Built-Up
        '''17	Other Urban Or Built-Up
        '''21	Cropland And Pasture
        '''22	Orch,Grov,Vnyrd,Nurs,Orn
        '''23	Confined Feeding Ops
        '''24	Other Agricultural Land
        '''41	Deciduous Forest Land
        '''42	Evergreen Forest Land
        '''43	Mixed Forest Land
        '''51	Streams And Canals
        '''52	Lakes
        '''53	Reservoirs
        '''61	Forested Wetland
        '''62	Nonforested Wetland
        '''75	Strip Mines
        '''76	Transitional Areas
        '''Num Cropping [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property LandUses() As String
            Get
                Return ResourceManager.GetString("LandUses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Muid	Description	HydGroup
        '''GAW	Water	
        '''GA001	Hartsells	D
        '''GA002	Hartsells	C
        '''GA003	Nella	B
        '''GA004	Shack	D
        '''GA005	Conasauga	D
        '''GA006	Shack	B
        '''GA007	Shack	C
        '''GA008	Minvale	D
        '''GA009	Holston	D
        '''GA010	Cunningham	C
        '''GA011	Townley	D
        '''GA012	Tupelo	B
        '''GA013	Colbert	C
        '''GA025	Madison	B
        '''GA026	Pacolet	B
        '''GA029	Tallapoosa	B
        '''GA030	Iredell	C
        '''GA034	Mountainburg	B
        '''GA037	Tallapoosa	A
        '''GA038	Vaucluse	A
        '''GA039	Vaucluse	A
        '''GA040	Lakeland	B
        '''GA041	Norfolk	B
        '''GA042	Wahee	D
        '''GA045	Meggett	D
        '''GA046	Orangeburg	B
        '''GA047	Chewacla	D [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SoilNames() As String
            Get
                Return ResourceManager.GetString("SoilNames", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
