'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("HSPEXP.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;DocumentElement&gt;
        '''  &lt;Parm&gt;
        '''    &lt;ParmID&gt;1&lt;/ParmID&gt;
        '''    &lt;OPNTYPE&gt;PERLND&lt;/OPNTYPE&gt;
        '''    &lt;TABLE&gt;PWAT-PARM2&lt;/TABLE&gt;
        '''    &lt;ParameterName&gt;LZSN&lt;/ParameterName&gt;
        '''    &lt;Min&gt;3&lt;/Min&gt;
        '''    &lt;Max&gt;8&lt;/Max&gt;
        '''  &lt;/Parm&gt;
        '''  &lt;Parm&gt;
        '''    &lt;ParmID&gt;2&lt;/ParmID&gt;
        '''    &lt;OPNTYPE&gt;PERLND&lt;/OPNTYPE&gt;
        '''    &lt;TABLE&gt;PWAT-PARM2&lt;/TABLE&gt;
        '''    &lt;ParameterName&gt;INFILT&lt;/ParameterName&gt;
        '''    &lt;Min&gt;0.001&lt;/Min&gt;
        '''    &lt;Max&gt;5&lt;/Max&gt;
        '''  &lt;/Parm&gt;
        '''  &lt;Parm&gt;
        '''    &lt;ParmID&gt;3&lt;/ParmID&gt;
        '''    &lt;OPNTYPE&gt;PERLND&lt;/OPNTYPE&gt;
        '''    &lt;TABLE&gt;PWAT-PARM2&lt;/TABLE&gt;
        '''    &lt;ParameterName&gt;SLSU [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property HSPFParmValues() As String
            Get
                Return ResourceManager.GetString("HSPFParmValues", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UCILandUse,GeneralLandUse
        '''Forest South HSG-lo,Forest
        '''Forest South HSG-hi,Forest
        '''Forest North HSG-lo,Forest
        '''Forest North HSG-hi,Forest
        '''PastureHay S HSG-lo,Pasture
        '''PastureHay S HSG-hi,Pasture
        '''PastureHay N HSG-lo,Pasture
        '''PastureHay N HSG-hi,Pasture
        '''Row Crops,Ag/Other
        '''Farmsteads,Ag/Other
        '''Urban/rec Grass,Urban
        '''Wetland/water,Wetland
        '''LowDensity Resident,Urban
        '''HighDensity Resident,Urban
        '''Comm/Indust/Trans,Urban
        '''Landslide/Sediment,Unknown
        '''Harbor Brook basin,Unknown
        '''Otisco Lake basin,Unknown
        '''FOREST, [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property LandUseNames_Mappings() As String
            Get
                Return ResourceManager.GetString("LandUseNames_Mappings", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
