'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("HSPEXP.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;ParameterRanges&gt;
        '''  &lt;Parm&gt;
        '''    &lt;PARMID&gt;1&lt;/PARMID&gt;
        '''    &lt;OPNTYPE&gt;PERLND&lt;/OPNTYPE&gt;
        '''    &lt;TABLE&gt;ACTIVITY&lt;/TABLE&gt;
        '''    &lt;ParameterName&gt;AIRTFG&lt;/ParameterName&gt;
        '''    &lt;ACTIVITYFLAG&gt;&lt;/ACTIVITYFLAG&gt;
        '''    &lt;ConstituentName&gt;&lt;/ConstituentName&gt;
        '''    &lt;IsMonthlyPossible&gt;&lt;/IsMonthlyPossible&gt;
        '''    &lt;Min&gt;0&lt;/Min&gt;
        '''    &lt;Max&gt;1&lt;/Max&gt;
        '''    &lt;Typical&gt;1&lt;/Typical&gt;
        '''    &lt;FlagTable&gt;&lt;/FlagTable&gt;
        '''    &lt;FlagParm&gt;&lt;/FlagParm&gt;
        '''    &lt;MonthlyParmTable&gt;&lt;/MonthlyParmTable&gt;
        '''    &lt;Notes&gt;&lt;/Notes&gt;
        '''  &lt;/Parm&gt;
        '''   [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property HSPFParmValues() As String
            Get
                Return ResourceManager.GetString("HSPFParmValues", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;landusemapping&gt;
        '''  &lt;landusename&gt;
        '''    &lt;UCILandUse&gt;Forest South HSG-lo&lt;/UCILandUse&gt;
        '''    &lt;GeneralLandUse&gt;Forest&lt;/GeneralLandUse&gt;
        '''  &lt;/landusename&gt;
        '''  &lt;landusename&gt;
        '''    &lt;UCILandUse&gt;Forest South HSG-hi&lt;/UCILandUse&gt;
        '''    &lt;GeneralLandUse&gt;Forest&lt;/GeneralLandUse&gt;
        '''  &lt;/landusename&gt;
        '''  &lt;landusename&gt;
        '''    &lt;UCILandUse&gt;Forest North HSG-lo&lt;/UCILandUse&gt;
        '''    &lt;GeneralLandUse&gt;Forest&lt;/GeneralLandUse&gt;
        '''  &lt;/landusename&gt;
        '''  &lt;landusename&gt;
        '''    &lt;UCILandUse&gt;Forest North HSG-hi&lt;/UCILandUse [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property LandUseNames_Mappings() As String
            Get
                Return ResourceManager.GetString("LandUseNames_Mappings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;&gt;
        '''  &lt;xsl:template match=&quot;/&quot;&gt;
        '''    &lt;html&gt;
        '''      &lt;head&gt;
        '''        &lt;style&gt;
        '''          table, th{
        '''          border:2px solid #DEDFE0;
        '''          border-collapse:collapse;
        '''          border-top-color: #ef3e32;
        '''          border-bottom-color: #ef3e32;
        '''          font-family: &quot;Arial Narrow&quot;, Arial, sans-serif; font-size: 14px;
        '''          }
        '''          td{
        '''          border:2px solid #DEDFE0;
        '''     [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property LimitViolatingParameterTemplate() As String
            Get
                Return ResourceManager.GetString("LimitViolatingParameterTemplate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        '''&lt;LoadingRates&gt;
        '''  &lt;Nutrient type=&quot;SED&quot;&gt;
        '''    &lt;Landuse name=&quot;Forest&quot;&gt;
        '''        &lt;Min&gt;100&lt;/Min&gt;
        '''        &lt;Max&gt;300&lt;/Max&gt;
        '''    &lt;/Landuse&gt;
        '''    &lt;Landuse name=&quot;Pasture&quot;&gt;
        '''        &lt;Min&gt;400&lt;/Min&gt;
        '''        &lt;Max&gt;2000&lt;/Max&gt;
        '''    &lt;/Landuse&gt;
        '''    &lt;Landuse name=&quot;Urban&quot;&gt;
        '''        &lt;Min&gt;300&lt;/Min&gt;
        '''        &lt;Max&gt;1000&lt;/Max&gt;
        '''    &lt;/Landuse&gt;
        '''    &lt;Landuse name=&quot;Ag/Other&quot;&gt;
        '''        &lt;Min&gt;200&lt;/Min&gt;
        '''        &lt;Max&gt;3000&lt;/Max&gt;
        '''    &lt;/Landuse&gt;
        '''    &lt;Landuse name=&quot;Wetland&quot;&gt;
        '''        &lt;Min&gt;0&lt;/Min&gt;
        '''   [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property LoadingRates() As String
            Get
                Return ResourceManager.GetString("LoadingRates", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
