'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("atcSediment.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Version	1
        '''Output name:	Project 1
        '''Grid cell size:	300
        '''Subbasins layer:	subbasin2
        '''Soil layer:	State Soil
        '''Soil type ID:	MUID
        '''Landuse type:	1
        '''Landuse layer:	NLCD_LandCover_1992
        '''Landuse ID:	
        '''Road layer:	
        '''Road ID:	
        '''DEM layer:	Digital Elevation Model
        '''DEM units:	Meters
        '''Rainfall factor:	300
        '''Num Erodibility:	346
        '''GA001	HARTSELLS	0.1904
        '''GA002	HARTSELLS	0.2345
        '''GA003	NELLA	0.2021
        '''GA004	SHACK	0.3633
        '''GA005	CONASAUGA	0.3772
        '''GA006	SHACK	0.2902
        '''GA007	SHACK	0.2778
        '''GA008	MINVALE	0.3327
        '''GA009	HOLSTON	0.321 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Defaults() As String
            Get
                Return ResourceManager.GetString("Defaults", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to State	County	Min R	Avg R	Max R
        '''Alabama	Autauga	375	375	375
        '''Alabama	Baldwin	550	550	550
        '''Alabama	Barbour	375	387	400
        '''Alabama	Bibb	375	375	375
        '''Alabama	Blount	325	325	325
        '''Alabama	Bullock	375	375	375
        '''Alabama	Butler	425	425	425
        '''Alabama	Calhoun	325	325	325
        '''Alabama	Chambers	325	337	350
        '''Alabama	Cherokee	300	300	300
        '''Alabama	Chilton	375	375	375
        '''Alabama	Choctaw	425	425	425
        '''Alabama	Clarke	450	450	450
        '''Alabama	Clay	350	350	350
        '''Alabama	Cleburne	325	325	325
        '''Alabama	Coffee	450	450	450
        '''Alabama	Colbert	300	300 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property R_Factors() As String
            Get
                Return ResourceManager.GetString("R_Factors", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
