Public Class ConduitShapefileSpecs
    Public ShapefileName As String = ""
    Public SubbasinFieldName As String = ""
    Public DownSubbasinFieldName As String = ""
    Public ElevHighFieldName As String = ""
    Public ElevLowFieldName As String = ""
    Public MeanWidthFieldName As String = ""
    Public MeanDepthFieldName As String = ""
    Public InletNodeFieldName As String = ""
    Public OutletNodeFieldName As String = ""
    Public ManningsNFieldName As String = ""
    Public InletOffsetFieldName As String = ""
    Public OutletOffsetFieldName As String = ""
    Public InitialFlowFieldName As String = ""
    Public MaxFlowFieldName As String = ""
    Public ShapeFieldName As String = ""
    Public Geometry1FieldName As String = ""
    Public Geometry2FieldName As String = ""
    Public Geometry3FieldName As String = ""
    Public Geometry4FieldName As String = ""
    Public NumBarrelsFieldName As String = ""
    Public CreateNodes As Boolean = True
End Class

Public Class CatchmentShapefileSpecs
    Public ShapefileName As String = ""
    Public SubbasinFieldName As String = ""
    Public OutletNodeFieldName As String = ""
    Public SlopeFieldName As String = ""
    Public WidthFieldName As String = ""
    Public CurbLengthFieldName As String = ""
    Public SnowPackNameFieldName As String = ""
    Public ManningsNImpervFieldName As String = ""
    Public ManningsNPervFieldName As String = ""
    Public DepressionStorageImpervFieldName As String = ""
    Public DepressionStoragePervFieldName As String = ""
    Public PercentZeroStorageFieldName As String = ""
    Public RouteToFieldName As String = ""
    Public PercentRoutedFieldName As String = ""
    Public MaxInfiltRateFieldName As String = ""
    Public MinInfiltRateFieldName As String = ""
    Public DecayRateConstantFieldName As String = ""
    Public DryTimeFieldName As String = ""
    Public MaxInfiltVolumeFieldName As String = ""
    Public SuctionFieldName As String = ""
    Public ConductivityFieldName As String = ""
    Public InitialDeficitFieldName As String = ""
    Public CurveNumberFieldName As String = ""
End Class


